package student.Views;

import java.awt.Component;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import student.Controllers.BatchController;
import student.Controllers.CourseController;
import student.Models.Course;
import student.Helpers.ComboItem;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author mpe20
 */
public class AddBatchView extends javax.swing.JFrame {
    
    private final CourseController courseController;
    private final BatchController batchController;
    
    Component panel = null;

    /**
     * Creates new form AddCourseView
     */
    public AddBatchView() {
        
        this.courseController = new CourseController();
        this.batchController = new BatchController();
        initComponents();

        ArrayList<Course> list = courseController.allCourses();
        int courseCount = courseController.allCourses().size();
        
        DefaultComboBoxModel cmbmodel = (DefaultComboBoxModel)cmb_course.getModel();
        
        for (int i = 0; i < courseCount; i++) {
            cmbmodel.addElement(new ComboItem(list.get(i).name, Integer.toString(list.get(i).id)));
        }
   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_number = new javax.swing.JTextField();
        lbl_id = new javax.swing.JLabel();
        lbl_id1 = new javax.swing.JLabel();
        cmb_course = new javax.swing.JComboBox<>();
        lbl_id2 = new javax.swing.JLabel();
        lbl_id3 = new javax.swing.JLabel();
        txt_regDate = new com.toedter.calendar.JDateChooser();
        btn_add = new java.awt.Button();
        lbl_id4 = new javax.swing.JLabel();
        txt_seats = new javax.swing.JTextField();
        lbl_id5 = new javax.swing.JLabel();
        txt_std_id = new javax.swing.JTextField();
        btn_edit = new java.awt.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lbl_id.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lbl_id.setText("Number :");

        lbl_id1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lbl_id1.setText("Registration Date :");

        lbl_id2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        lbl_id3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lbl_id3.setText("Seats : ");

        btn_add.setLabel("Add");
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });

        lbl_id4.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lbl_id4.setText("Course :");

        lbl_id5.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lbl_id5.setText("Student ID :");

        btn_edit.setLabel("Edit");
        btn_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmb_course, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_id5)
                    .addComponent(lbl_id)
                    .addComponent(lbl_id4)
                    .addComponent(txt_seats, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_id1)
                    .addComponent(lbl_id3)
                    .addComponent(txt_regDate, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_add, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbl_id2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txt_std_id, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txt_number, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 419, Short.MAX_VALUE)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(lbl_id5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_std_id, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_id2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_id)
                .addGap(13, 13, 13)
                .addComponent(txt_number, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_id3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_seats, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(lbl_id4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmb_course, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_id1)
                .addGap(18, 18, 18)
                .addComponent(txt_regDate, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_add, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed

        
        Object item = cmb_course.getSelectedItem();
        String course_id = ((ComboItem)item).getValue();
        
        String number = txt_number.getText();
        String seats = txt_seats.getText();
        Date reg_date = txt_regDate.getDate();
       

        if(number == null || reg_date == null || number.length() == 0) {
             JOptionPane.showMessageDialog(panel, "All fields are required", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            java.sql.Date date = new java.sql.Date(reg_date.getTime());
            batchController.insertBatch(number, Integer.parseInt(seats), Integer.parseInt(course_id), date);
            JOptionPane.showMessageDialog(panel, "Batch added successful", "Success", JOptionPane.INFORMATION_MESSAGE);
        }
        
    }//GEN-LAST:event_btn_addActionPerformed

    private void btn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editActionPerformed
        JOptionPane.showMessageDialog(panel, "Batch edited successful", "Success", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btn_editActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddBatchView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddBatchView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddBatchView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddBatchView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new AddBatchView().setVisible(true);
            }
        });
    }
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button btn_add;
    private java.awt.Button btn_edit;
    private javax.swing.JComboBox<String> cmb_course;
    private javax.swing.JLabel lbl_id;
    private javax.swing.JLabel lbl_id1;
    private javax.swing.JLabel lbl_id2;
    private javax.swing.JLabel lbl_id3;
    private javax.swing.JLabel lbl_id4;
    private javax.swing.JLabel lbl_id5;
    private javax.swing.JTextField txt_number;
    private com.toedter.calendar.JDateChooser txt_regDate;
    private javax.swing.JTextField txt_seats;
    private javax.swing.JTextField txt_std_id;
    // End of variables declaration//GEN-END:variables
}
