/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package student.Views;

import java.awt.Component;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import student.Controllers.CourseController;
import student.Controllers.GradeController;
import student.Controllers.StudentController;
import student.Controllers.SubjectController;
import student.Helpers.ComboItem;
import student.Models.Course;
import student.Models.Student;
import student.Models.Subject;

/**
 *
 * @author mpe20
 */
public class AddGrade extends javax.swing.JFrame {
    
    private final StudentController studentController;
    private final CourseController courseController;
    private final SubjectController subjectController;
    private final GradeController gradeController;
    
    private Integer studentId = 0;
    Component panel = null;

    /**
     * Creates new form AddGrade
     */
    public AddGrade() {
        this.studentController = new StudentController();
        this.courseController = new CourseController();
        this.subjectController = new SubjectController();
        this.gradeController = new GradeController();
        initComponents();
        
        //Course List
        ArrayList<Course> list = courseController.allCourses();
        int courseCount = courseController.allCourses().size();
        
        DefaultComboBoxModel cmbmodel = (DefaultComboBoxModel)cmb_courses.getModel();
        
        for (int i = 0; i < courseCount; i++) {
            cmbmodel.addElement(new ComboItem(list.get(i).name, Integer.toString(list.get(i).id)));
        }
        
        //Subject List
        ArrayList<Subject> list2 = subjectController.allSubjects();
        int subjectCount = subjectController.allSubjects().size();
        
        DefaultComboBoxModel cmbmodel2 = (DefaultComboBoxModel)cmb_subjects.getModel();
        
        for (int j= 0; j < subjectCount; j++) {
            cmbmodel2.addElement(new ComboItem(list2.get(j).name, Integer.toString(list2.get(j).id)));
        }
        
        //Grades
        
        DefaultComboBoxModel cmbmodel3 = (DefaultComboBoxModel)cmb_grades.getModel();
        cmbmodel3.addElement(new ComboItem("Distinction", "d"));
        cmbmodel3.addElement(new ComboItem("Merit", "m"));
        cmbmodel3.addElement(new ComboItem("Pass", "p"));
        cmbmodel3.addElement(new ComboItem("Resubmit", "r"));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_stdid = new javax.swing.JLabel();
        txt_stdid = new javax.swing.JTextField();
        btn_selectStu = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        cmb_course = new javax.swing.JComboBox<>();
        lbl_stdid1 = new javax.swing.JLabel();
        txt_std = new javax.swing.JTextField();
        btn_slStu = new javax.swing.JButton();
        lbl_stdid2 = new javax.swing.JLabel();
        cmb_grades = new javax.swing.JComboBox<>();
        lbl_stdid3 = new javax.swing.JLabel();
        cmb_courses = new javax.swing.JComboBox<>();
        lbl_stdid4 = new javax.swing.JLabel();
        cmb_subjects = new javax.swing.JComboBox<>();
        btn_addGrade = new javax.swing.JButton();

        lbl_stdid.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lbl_stdid.setText("Student ID :");

        btn_selectStu.setText("Select Student");
        btn_selectStu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_selectStuActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lbl_stdid1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lbl_stdid1.setText("Student ID :");

        btn_slStu.setText("Select Student");
        btn_slStu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_slStuActionPerformed(evt);
            }
        });

        lbl_stdid2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lbl_stdid2.setText("Select Course : ");

        lbl_stdid3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lbl_stdid3.setText("Select Subject : ");

        lbl_stdid4.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lbl_stdid4.setText("Select Grade : ");

        btn_addGrade.setText("Add Grade");
        btn_addGrade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addGradeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txt_std)
                        .addGap(28, 28, 28))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_stdid1)
                            .addComponent(btn_slStu, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(172, 172, 172)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_addGrade, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmb_subjects, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_stdid4)
                    .addComponent(lbl_stdid3)
                    .addComponent(cmb_grades, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_stdid2)
                    .addComponent(cmb_courses, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_stdid2)
                                .addGap(8, 8, 8)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cmb_courses, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_std, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(lbl_stdid1))
                        .addGap(18, 18, 18)
                        .addComponent(lbl_stdid3))
                    .addComponent(btn_slStu, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addComponent(cmb_subjects, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_stdid4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmb_grades, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_addGrade, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        lbl_stdid2.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_selectStuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_selectStuActionPerformed

       
        
    }//GEN-LAST:event_btn_selectStuActionPerformed

    private void btn_slStuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_slStuActionPerformed
        
        String stdid = txt_std.getText();
        
        if(stdid == null || stdid.length() == 0) {
            JOptionPane.showMessageDialog(panel, "Student id is requied", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            
            Student stu = studentController.searchById(Integer.parseInt(stdid));
        
            if(stu != null) {
                studentId = stu.id;
                 JOptionPane.showMessageDialog(panel, "Student Selected", "Success", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(panel, "Student Not Found In the Database", "Error", JOptionPane.ERROR_MESSAGE);
               
            }
        }
    }//GEN-LAST:event_btn_slStuActionPerformed

    private void btn_addGradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addGradeActionPerformed
        
        Object courseItem = cmb_courses.getSelectedItem();
        String course_id = ((ComboItem)courseItem).getValue();
        
        Object subjectItem = cmb_subjects.getSelectedItem();
        String subject_id = ((ComboItem)subjectItem).getValue();
        
        Object gradeItem = cmb_grades.getSelectedItem();
        String grade = ((ComboItem)gradeItem ).getValue();
        
         
        if(studentId == 0) {
            JOptionPane.showMessageDialog(panel, "Student ID Error", "Error", JOptionPane.ERROR_MESSAGE);
        }else if(course_id  == null || course_id.length() == 0) {
            JOptionPane.showMessageDialog(panel, "Course ID Error", "Error", JOptionPane.ERROR_MESSAGE);
        }else if(subject_id  == null || course_id.length() == 0) {
            JOptionPane.showMessageDialog(panel, "Subject ID Error", "Error", JOptionPane.ERROR_MESSAGE);
        }else if(grade  == null || grade.length() == 0) {
            JOptionPane.showMessageDialog(panel, "Grade Error", "Error", JOptionPane.ERROR_MESSAGE);
        }
        else {
            gradeController.insertGrade(grade, Integer.parseInt(course_id), studentId, Integer.parseInt(subject_id));
            JOptionPane.showMessageDialog(panel, "Grade Added Successful", "Success", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btn_addGradeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddGrade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddGrade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddGrade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddGrade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddGrade().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_addGrade;
    private javax.swing.JButton btn_selectStu;
    private javax.swing.JButton btn_slStu;
    private javax.swing.JComboBox<String> cmb_course;
    private javax.swing.JComboBox<String> cmb_courses;
    private javax.swing.JComboBox<String> cmb_grades;
    private javax.swing.JComboBox<String> cmb_subjects;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbl_stdid;
    private javax.swing.JLabel lbl_stdid1;
    private javax.swing.JLabel lbl_stdid2;
    private javax.swing.JLabel lbl_stdid3;
    private javax.swing.JLabel lbl_stdid4;
    private javax.swing.JTextField txt_std;
    private javax.swing.JTextField txt_stdid;
    // End of variables declaration//GEN-END:variables
}
