package student.Views;

import student.Controllers.StudentController;
import java.awt.Component;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author mpe20
 */
public class AddStudentView extends javax.swing.JFrame {
    
    private final StudentController studentController;
    Component panel = null;


    /**
     * Creates new form AddStudent
     */
    public AddStudentView() {
        this.studentController = new StudentController();
        initComponents();
        
        String nextid = Integer.toString(studentController.nextStudentId() + 1);
        txt_regid.setText("COL-" + nextid);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textField1 = new java.awt.TextField();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        lbl_id = new javax.swing.JLabel();
        txt_regid = new javax.swing.JTextField();
        lbl_name = new javax.swing.JLabel();
        btn_register = new javax.swing.JButton();
        lbl_address = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_address = new javax.swing.JTextArea();
        lbl_contact = new javax.swing.JLabel();
        lbl_nic = new javax.swing.JLabel();
        lbl_dob = new javax.swing.JLabel();
        txt_name = new javax.swing.JTextField();
        txt_BMonth = new javax.swing.JTextField();
        txt_nic1 = new javax.swing.JTextField();
        txt_contact1 = new javax.swing.JTextField();
        txt_BYear = new javax.swing.JTextField();
        txt_BDay = new javax.swing.JTextField();
        btn_edit = new javax.swing.JButton();

        textField1.setText("textField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lbl_id.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lbl_id.setText("Student Reg ID :");

        txt_regid.setEditable(false);

        lbl_name.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lbl_name.setText("Student Name :");

        btn_register.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btn_register.setText("Register");
        btn_register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registerActionPerformed(evt);
            }
        });

        lbl_address.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lbl_address.setText("Student Address :");

        txt_address.setColumns(20);
        txt_address.setRows(5);
        jScrollPane1.setViewportView(txt_address);

        lbl_contact.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lbl_contact.setText("Student Contact :");

        lbl_nic.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lbl_nic.setText("Student NIC :");

        lbl_dob.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lbl_dob.setText("Student DOB:");

        txt_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nameActionPerformed(evt);
            }
        });

        txt_BMonth.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_BMonth.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_BMonth.setText("02");
        txt_BMonth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_BMonthActionPerformed(evt);
            }
        });

        txt_nic1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nic1ActionPerformed(evt);
            }
        });

        txt_contact1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_contact1ActionPerformed(evt);
            }
        });

        txt_BYear.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_BYear.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_BYear.setText("1992");
        txt_BYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_BYearActionPerformed(evt);
            }
        });

        txt_BDay.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_BDay.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_BDay.setText("25");
        txt_BDay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_BDayActionPerformed(evt);
            }
        });

        btn_edit.setText("Edit");
        btn_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txt_BYear, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_BMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_BDay, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lbl_dob)
                        .addComponent(lbl_address)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btn_register)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btn_edit))
                        .addComponent(lbl_name)
                        .addComponent(lbl_id)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 441, Short.MAX_VALUE)
                        .addComponent(lbl_contact)
                        .addComponent(txt_regid)
                        .addComponent(lbl_nic)
                        .addComponent(txt_name)
                        .addComponent(txt_nic1)
                        .addComponent(txt_contact1)))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lbl_id)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_regid, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_name)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_name, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_nic)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_nic1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(lbl_address)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_contact)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_contact1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(lbl_dob)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_BYear, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_BMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_BDay, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_register)
                    .addComponent(btn_edit))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registerActionPerformed
         
              
       String reg_id = txt_regid.getText();
       String name = txt_name.getText();
       String nic = txt_BMonth.getText();
       String address = txt_address.getText();
       String contact = txt_BMonth.getText();
       String bYear = txt_BYear.getText();
       String bMonth = txt_BMonth.getText();
       String bDay = txt_BDay.getText();
       
       String dob = bYear+'-'+bMonth+'-'+bDay;
       
        
       if(((((((((((((((reg_id == null || name == null) || nic == null) || address == null) || contact == null) || bYear == null) || bMonth == null) || bDay == null) || reg_id.length() == 0) || name.length() == 0) || nic.length() == 0) || address.length() == 0) || contact.length() == 0) || bYear.length() == 0) || bMonth.length() == 0) || bDay.length() == 0) {
           
           JOptionPane.showMessageDialog(panel, "All fields are required", "Error", JOptionPane.ERROR_MESSAGE);
       } else {
           studentController.insertStudent(reg_id, name, address, contact, nic, dob);
           JOptionPane.showMessageDialog(panel, "Student added successful", "Success", JOptionPane.INFORMATION_MESSAGE);
       }
    

    }//GEN-LAST:event_btn_registerActionPerformed

    private void txt_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nameActionPerformed

    private void txt_BMonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_BMonthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_BMonthActionPerformed

    private void txt_nic1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nic1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nic1ActionPerformed

    private void txt_contact1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_contact1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_contact1ActionPerformed

    private void txt_BYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_BYearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_BYearActionPerformed

    private void txt_BDayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_BDayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_BDayActionPerformed

    private void btn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editActionPerformed
        JOptionPane.showMessageDialog(panel, "Student edited successful", "Success", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btn_editActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddStudentView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddStudentView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddStudentView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddStudentView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new AddStudentView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_edit;
    private javax.swing.JButton btn_register;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_address;
    private javax.swing.JLabel lbl_contact;
    private javax.swing.JLabel lbl_dob;
    private javax.swing.JLabel lbl_id;
    private javax.swing.JLabel lbl_name;
    private javax.swing.JLabel lbl_nic;
    private java.awt.TextField textField1;
    private javax.swing.JTextField txt_BDay;
    private javax.swing.JTextField txt_BMonth;
    private javax.swing.JTextField txt_BYear;
    private javax.swing.JTextArea txt_address;
    private javax.swing.JTextField txt_contact1;
    private javax.swing.JTextField txt_name;
    private javax.swing.JTextField txt_nic1;
    private javax.swing.JTextField txt_regid;
    // End of variables declaration//GEN-END:variables
}
