/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package student.Views;

import java.awt.Component;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import student.Controllers.StudentController;
import student.Models.Course;
import student.Models.Student;

/**
 *
 * @author mpe20
 */
public class StudentView extends javax.swing.JFrame {
    
    private final StudentController studentController;
    Component panel = null;

    /**
     * Creates new form StudentView
     */
    public StudentView() {
        this.studentController = new StudentController();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_stdid = new javax.swing.JTextField();
        btn_selectStu = new javax.swing.JButton();
        lbl_name = new javax.swing.JLabel();
        txt_nic = new javax.swing.JTextField();
        txt_name = new javax.swing.JTextField();
        lbl_name2 = new javax.swing.JLabel();
        lbl_stdid = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lbl_name3 = new javax.swing.JLabel();
        txt_regid = new javax.swing.JTextField();
        lbl_name4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_address = new javax.swing.JTextArea();
        txt_contact = new javax.swing.JTextField();
        lbl_name5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_scourse = new javax.swing.JTable();
        lbl_stdid1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btn_selectStu.setText("Select Student");
        btn_selectStu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_selectStuActionPerformed(evt);
            }
        });

        lbl_name.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lbl_name.setText("Student Name :");

        txt_nic.setEditable(false);
        txt_nic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nicActionPerformed(evt);
            }
        });

        txt_name.setEditable(false);
        txt_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nameActionPerformed(evt);
            }
        });

        lbl_name2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lbl_name2.setText("Student Address :");

        lbl_stdid.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lbl_stdid.setText("Student ID :");

        lbl_name3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lbl_name3.setText("Student Reg ID :");

        txt_regid.setEditable(false);
        txt_regid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_regidActionPerformed(evt);
            }
        });

        lbl_name4.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lbl_name4.setText("Student NIC :");

        txt_address.setEditable(false);
        txt_address.setColumns(20);
        txt_address.setRows(5);
        jScrollPane1.setViewportView(txt_address);

        txt_contact.setEditable(false);
        txt_contact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_contactActionPerformed(evt);
            }
        });

        lbl_name5.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lbl_name5.setText("Student Contact:");

        tbl_scourse.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbl_scourse.setToolTipText("");
        jScrollPane2.setViewportView(tbl_scourse);

        lbl_stdid1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lbl_stdid1.setText("Student Courses :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_name2)
                    .addComponent(lbl_name5)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txt_contact, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)
                        .addComponent(txt_nic, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txt_name, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txt_regid, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lbl_stdid, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lbl_name3, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btn_selectStu, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbl_name4, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lbl_name, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txt_stdid, javax.swing.GroupLayout.Alignment.LEADING)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_stdid1))
                .addGap(39, 39, 39))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_stdid)
                    .addComponent(lbl_stdid1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txt_stdid, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_selectStu, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbl_name3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_regid, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbl_name)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_name, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbl_name4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_nic, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbl_name2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbl_name5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_contact, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_selectStuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_selectStuActionPerformed
        String stdid = txt_stdid.getText();

        if(stdid == null || stdid.length() == 0) {
            JOptionPane.showMessageDialog(panel, "Student id is requied", "Error", JOptionPane.ERROR_MESSAGE);
        } else {

            Student stu = studentController.searchById(Integer.parseInt(stdid));

            if(stu != null) {
                
                txt_regid.setText(stu.regid);
                txt_name.setText(stu.name);
                txt_nic.setText(stu.nic);
                txt_address.setText(stu.address);
                txt_contact.setText(stu.contact);
                
                
                DefaultTableModel amodel = (DefaultTableModel)tbl_scourse.getModel();
                amodel.setRowCount(0);

                String colHeads[] = {"ID", "Name"};
                amodel.setColumnIdentifiers(colHeads);

                ArrayList<Course> list = studentController.studentCourseList(stu.id);
                int courseCount = studentController.studentCourseList(stu.id).size();

                Object rowData[] =  new Object[2];

                for (int i = 0; i < courseCount; i++) {
                   rowData[0] =  list.get(i).id;
                   rowData[1] =  list.get(i).name;

                   amodel.addRow(rowData);
                }

            } else {
                txt_name.setText("");
                txt_nic.setText("");
                JOptionPane.showMessageDialog(panel, "Student Not Found In the Database", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btn_selectStuActionPerformed

    private void txt_nicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nicActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nicActionPerformed

    private void txt_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nameActionPerformed

    private void txt_regidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_regidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_regidActionPerformed

    private void txt_contactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_contactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_contactActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_selectStu;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbl_name;
    private javax.swing.JLabel lbl_name2;
    private javax.swing.JLabel lbl_name3;
    private javax.swing.JLabel lbl_name4;
    private javax.swing.JLabel lbl_name5;
    private javax.swing.JLabel lbl_stdid;
    private javax.swing.JLabel lbl_stdid1;
    private javax.swing.JTable tbl_scourse;
    private javax.swing.JTextArea txt_address;
    private javax.swing.JTextField txt_contact;
    private javax.swing.JTextField txt_name;
    private javax.swing.JTextField txt_nic;
    private javax.swing.JTextField txt_regid;
    private javax.swing.JTextField txt_stdid;
    // End of variables declaration//GEN-END:variables
}
