/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package student.Views;

import java.awt.Component;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import student.Controllers.BatchController;
import student.Controllers.CourseController;
import student.Controllers.EnrollController;
import student.Controllers.MajorController;
import student.Controllers.StudentController;
import student.Helpers.ComboItem;
import student.Models.Batch;
import student.Models.Course;
import student.Models.Major;
import student.Models.Student;

/**
 *
 * @author mpe20
 */
public class StudentEnrollView extends javax.swing.JFrame {
    
    private final StudentController studentController;
    private final CourseController courseController;
    private final BatchController batchController;
    private final MajorController majorController;
    private final EnrollController enrollController;
    
    private Integer studentId = 0;
    Component panel = null;

    /**
     * Creates new form StudentEnrollView
     */
    public StudentEnrollView() {
        
        this.courseController = new CourseController();
        this.studentController = new StudentController();
        this.batchController = new BatchController();
        this.majorController  = new MajorController();
        this.enrollController = new EnrollController();
        
        initComponents();
        
        //Course List
        ArrayList<Course> list = courseController.allCourses();
        int courseCount = courseController.allCourses().size();
        
        DefaultComboBoxModel cmbmodel = (DefaultComboBoxModel)cmb_course.getModel();
        
        for (int i = 0; i < courseCount; i++) {
            cmbmodel.addElement(new ComboItem(list.get(i).name, Integer.toString(list.get(i).id)));
        }
        
        //Batch List
        ArrayList<Batch> list2 = batchController.allBatches();
        int batchCount = batchController.allBatches().size();
        
        DefaultComboBoxModel cmbmodel2 = (DefaultComboBoxModel)cmb_batch.getModel();
        
        for (int j = 0; j < batchCount; j++) {
            cmbmodel2.addElement(new ComboItem(list2.get(j).number, Integer.toString(list2.get(j).id)));
        }
        
        //Major List
        ArrayList<Major> list3 = majorController.allMajors();
        int majorCount = majorController.allMajors().size();
        
        DefaultComboBoxModel cmbmodel3 = (DefaultComboBoxModel)cmb_major.getModel();
        
        for (int x = 0; x < majorCount; x++) {
            cmbmodel3.addElement(new ComboItem(list3.get(x).name, Integer.toString(list3.get(x).id)));
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_stdid = new javax.swing.JLabel();
        txt_stdid = new javax.swing.JTextField();
        lbl_name3 = new javax.swing.JLabel();
        cmb_batch = new javax.swing.JComboBox<>();
        btn_checkSeats = new javax.swing.JButton();
        lbl_name4 = new javax.swing.JLabel();
        lbl_name = new javax.swing.JLabel();
        txt_nic = new javax.swing.JTextField();
        txt_name = new javax.swing.JTextField();
        lbl_name2 = new javax.swing.JLabel();
        lbl_name1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        cmb_major = new javax.swing.JComboBox<>();
        btn_selectStu = new javax.swing.JButton();
        btn_enroll = new javax.swing.JButton();
        cmb_course = new javax.swing.JComboBox<>();
        txt_date = new com.toedter.calendar.JDateChooser();
        lbl_name5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lbl_stdid.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lbl_stdid.setText("Student ID :");

        lbl_name3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lbl_name3.setText("Batch : ");

        btn_checkSeats.setText("Check Seats");
        btn_checkSeats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_checkSeatsActionPerformed(evt);
            }
        });

        lbl_name4.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lbl_name4.setText("Major :");

        lbl_name.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lbl_name.setText("Student Name :");

        txt_nic.setEditable(false);
        txt_nic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nicActionPerformed(evt);
            }
        });

        txt_name.setEditable(false);
        txt_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nameActionPerformed(evt);
            }
        });

        lbl_name2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lbl_name2.setText("Student NIC :");

        lbl_name1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lbl_name1.setText("Course : ");

        btn_selectStu.setText("Select Student");
        btn_selectStu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_selectStuActionPerformed(evt);
            }
        });

        btn_enroll.setText("Enroll Course");
        btn_enroll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_enrollActionPerformed(evt);
            }
        });

        lbl_name5.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lbl_name5.setText("Enroll Date :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_stdid)
                            .addComponent(btn_selectStu, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(212, 212, 212))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_stdid)
                            .addComponent(jSeparator1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_name2)
                                    .addComponent(lbl_name))
                                .addGap(164, 164, 164))
                            .addComponent(txt_nic)
                            .addComponent(txt_name))
                        .addGap(48, 48, 48)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_name1)
                            .addComponent(lbl_name3)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(cmb_batch, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btn_checkSeats))
                                .addComponent(cmb_course, javax.swing.GroupLayout.Alignment.LEADING, 0, 393, Short.MAX_VALUE))
                            .addComponent(lbl_name4))
                        .addComponent(btn_enroll)
                        .addComponent(cmb_major, 0, 393, Short.MAX_VALUE)
                        .addComponent(txt_date, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(lbl_name5))
                .addGap(34, 34, 34))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_stdid)
                        .addGap(13, 13, 13)
                        .addComponent(txt_stdid, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_selectStu, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(lbl_name)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_name, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbl_name2))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_name1)
                                .addGap(13, 13, 13)
                                .addComponent(cmb_course, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(49, 49, 49))
                            .addComponent(lbl_name3))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cmb_batch, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn_checkSeats, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(78, 78, 78)
                                .addComponent(lbl_name4)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmb_major, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(lbl_name5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_date, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE))
                    .addComponent(txt_nic, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btn_enroll, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_nicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nicActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nicActionPerformed

    private void txt_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nameActionPerformed

    private void btn_selectStuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_selectStuActionPerformed
        String stdid = txt_stdid.getText();
        
        
        if(stdid == null || stdid.length() == 0) {
            JOptionPane.showMessageDialog(panel, "Student id is requied", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            
            Student stu = studentController.searchById(Integer.parseInt(stdid));
        
            if(stu != null) {
                
                studentId = stu.id;

                txt_name.setText(stu.name);
                txt_nic.setText(stu.nic);

            } else {
                txt_name.setText("");
                txt_nic.setText("");
                JOptionPane.showMessageDialog(panel, "Student Not Found In the Database", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btn_selectStuActionPerformed

    private void btn_enrollActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_enrollActionPerformed

        
        Object courseItem = cmb_course.getSelectedItem();
        String course_id = ((ComboItem)courseItem).getValue();
        
        Object batchItem = cmb_batch.getSelectedItem();
        String batch_id = ((ComboItem)batchItem ).getValue();
        
        Object majorItem = cmb_major.getSelectedItem();
        String major_id = ((ComboItem)majorItem).getValue();
        
        Date enDate = txt_date.getDate();
        
        
        if(studentId == 0) {
            JOptionPane.showMessageDialog(panel, "Student ID Error", "Error", JOptionPane.ERROR_MESSAGE);
        } else if(batch_id == null || batch_id.length() == 0) {
            JOptionPane.showMessageDialog(panel, "Batch ID Error", "Error", JOptionPane.ERROR_MESSAGE);
        } else if(course_id == null || course_id.length() == 0) {
            JOptionPane.showMessageDialog(panel, "Course ID Error", "Error", JOptionPane.ERROR_MESSAGE);
        }else if(major_id == null || major_id.length() == 0) {
            JOptionPane.showMessageDialog(panel, "Major ID Error", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            java.sql.Date date = new java.sql.Date(enDate.getTime());
            enrollController.insertEnroll(studentId, Integer.parseInt(course_id), Integer.parseInt(batch_id), Integer.parseInt(major_id), date);
            JOptionPane.showMessageDialog(panel, "Student Enrolled Successful", "Success", JOptionPane.INFORMATION_MESSAGE);
        }
        
    }//GEN-LAST:event_btn_enrollActionPerformed

    private void btn_checkSeatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_checkSeatsActionPerformed
       
        Object batchItem = cmb_batch.getSelectedItem();
        String batchID = ((ComboItem)batchItem ).getValue();
        
        if(enrollController.seatsAvaliable(Integer.parseInt(batchID))) {
            JOptionPane.showMessageDialog(panel, "Seats Available", "Success", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(panel, "Seats Not Available", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_checkSeatsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentEnrollView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentEnrollView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentEnrollView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentEnrollView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentEnrollView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_checkSeats;
    private javax.swing.JButton btn_enroll;
    private javax.swing.JButton btn_selectStu;
    private javax.swing.JComboBox<String> cmb_batch;
    private javax.swing.JComboBox<String> cmb_course;
    private javax.swing.JComboBox<String> cmb_major;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbl_name;
    private javax.swing.JLabel lbl_name1;
    private javax.swing.JLabel lbl_name2;
    private javax.swing.JLabel lbl_name3;
    private javax.swing.JLabel lbl_name4;
    private javax.swing.JLabel lbl_name5;
    private javax.swing.JLabel lbl_stdid;
    private com.toedter.calendar.JDateChooser txt_date;
    private javax.swing.JTextField txt_name;
    private javax.swing.JTextField txt_nic;
    private javax.swing.JTextField txt_stdid;
    // End of variables declaration//GEN-END:variables
}
